// <auto-generated />
using System;
using FoodEcomerce.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodEcomerce.Migrations
{
    [DbContext(typeof(FoodDbContex))]
    [Migration("20250816234312_fix")]
    partial class fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodEcomerce.Entity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Category");

                    b.HasIndex("CategoryParentId");

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("FoodEcomerce.Entity.ImageProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ImageProduct");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MenuParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenuParentId");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.MenuRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Add")
                        .HasColumnType("bit");

                    b.Property<bool?>("Delete")
                        .HasColumnType("bit");

                    b.Property<bool?>("Update")
                        .HasColumnType("bit");

                    b.Property<bool?>("Watch")
                        .HasColumnType("bit");

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("MenuRole");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.Panner", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Panner");

                    b.ToTable("Panner", (string)null);
                });

            modelBuilder.Entity("FoodEcomerce.Entity.PlaceProduct", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_PlaceProduct");

                    b.ToTable("PlaceProduct", (string)null);
                });

            modelBuilder.Entity("FoodEcomerce.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("Inventory")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlaceProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal");

                    b.Property<int>("TradeMarkId")
                        .HasColumnType("int");

                    b.Property<Guid>("UnitCaculateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("double");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Product");

                    b.HasIndex("PlaceProductId");

                    b.HasIndex("UnitCaculateId");

                    b.ToTable("Product", (string)null);
                });

            modelBuilder.Entity("FoodEcomerce.Entity.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategory");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Role");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("FoodEcomerce.Entity.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Status");

                    b.ToTable("Status", (string)null);
                });

            modelBuilder.Entity("FoodEcomerce.Entity.TradeMark", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Discription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool?>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_TradeMark");

                    b.ToTable("TradeMark", (string)null);
                });

            modelBuilder.Entity("FoodEcomerce.Entity.UnitCaculate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BaseUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("ConservationRate")
                        .HasColumnType("decimal");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_UnitCaculate");

                    b.HasIndex("BaseUnitId");

                    b.ToTable("UnitCaculate", (string)null);
                });

            modelBuilder.Entity("FoodEcomerce.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Acvite")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_User");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("FoodEcomerce.Entity.Category", b =>
                {
                    b.HasOne("FoodEcomerce.Entity.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("CategoryParentId")
                        .IsRequired()
                        .HasConstraintName("FK_ParentCategory");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.ImageProduct", b =>
                {
                    b.HasOne("FoodEcomerce.Entity.Product", "Product")
                        .WithMany("ImageProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.Menu", b =>
                {
                    b.HasOne("FoodEcomerce.Entity.Menu", "MenuParent")
                        .WithMany("Menus")
                        .HasForeignKey("MenuParentId");

                    b.Navigation("MenuParent");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.MenuRole", b =>
                {
                    b.HasOne("FoodEcomerce.Entity.Menu", "Menu")
                        .WithMany("MenuRoles")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MenuRole_Menu");

                    b.HasOne("FoodEcomerce.Entity.Role", "Role")
                        .WithMany("MenuRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MenuRole_Role");

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.Product", b =>
                {
                    b.HasOne("FoodEcomerce.Entity.PlaceProduct", "PlaceProduct")
                        .WithMany("Products")
                        .HasForeignKey("PlaceProductId")
                        .IsRequired()
                        .HasConstraintName("FK_PlaceProduct_Products");

                    b.HasOne("FoodEcomerce.Entity.TradeMark", "TradeMark")
                        .WithMany("Products")
                        .HasForeignKey("PlaceProductId")
                        .IsRequired()
                        .HasConstraintName("FK_TradeMark_Products");

                    b.HasOne("FoodEcomerce.Entity.UnitCaculate", "UnitCaculate")
                        .WithMany("Products")
                        .HasForeignKey("UnitCaculateId")
                        .IsRequired()
                        .HasConstraintName("FK_UnitCaculate_Products");

                    b.Navigation("PlaceProduct");

                    b.Navigation("TradeMark");

                    b.Navigation("UnitCaculate");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.ProductCategory", b =>
                {
                    b.HasOne("FoodEcomerce.Entity.Category", "Categories")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Category_ProductCategory");

                    b.HasOne("FoodEcomerce.Entity.Product", "Products")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Product_ProductCategory");

                    b.Navigation("Categories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.UnitCaculate", b =>
                {
                    b.HasOne("FoodEcomerce.Entity.UnitCaculate", "ParentUnitCaculate")
                        .WithMany("SubUnitCaculates")
                        .HasForeignKey("BaseUnitId")
                        .IsRequired()
                        .HasConstraintName("FK_ParentUnitCaculate");

                    b.Navigation("ParentUnitCaculate");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.User", b =>
                {
                    b.HasOne("FoodEcomerce.Entity.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Role_User");

                    b.HasOne("FoodEcomerce.Entity.Status", "Status")
                        .WithMany("Users")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_Status_User");

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.Menu", b =>
                {
                    b.Navigation("MenuRoles");

                    b.Navigation("Menus");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.PlaceProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.Product", b =>
                {
                    b.Navigation("ImageProducts");

                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.Role", b =>
                {
                    b.Navigation("MenuRoles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.Status", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.TradeMark", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("FoodEcomerce.Entity.UnitCaculate", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubUnitCaculates");
                });
#pragma warning restore 612, 618
        }
    }
}
