/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DangNhapIndexRouteImport } from './routes/DangNhap/index'
import { Route as DangKyIndexRouteImport } from './routes/DangKy/index'
import { Route as AdminDashboardRouteRouteImport } from './routes/admin/Dashboard/route'
import { Route as AdminDashboardMenuIndexRouteImport } from './routes/admin/Dashboard/Menu/index'
import { Route as AdminDashboardLoaiTaiKhoanIndexRouteImport } from './routes/admin/Dashboard/LoaiTaiKhoan/index'
import { Route as AdminDashboardDanhMucIndexRouteImport } from './routes/admin/Dashboard/DanhMuc/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapIndexRoute = DangNhapIndexRouteImport.update({
  id: '/DangNhap/',
  path: '/DangNhap/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyIndexRoute = DangKyIndexRouteImport.update({
  id: '/DangKy/',
  path: '/DangKy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/admin/Dashboard',
  path: '/admin/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardMenuIndexRoute = AdminDashboardMenuIndexRouteImport.update({
  id: '/Menu/',
  path: '/Menu/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardLoaiTaiKhoanIndexRoute =
  AdminDashboardLoaiTaiKhoanIndexRouteImport.update({
    id: '/LoaiTaiKhoan/',
    path: '/LoaiTaiKhoan/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardDanhMucIndexRoute =
  AdminDashboardDanhMucIndexRouteImport.update({
    id: '/DanhMuc/',
    path: '/DanhMuc/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/Dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/DangKy': typeof DangKyIndexRoute
  '/DangNhap': typeof DangNhapIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/Dashboard/DanhMuc': typeof AdminDashboardDanhMucIndexRoute
  '/admin/Dashboard/LoaiTaiKhoan': typeof AdminDashboardLoaiTaiKhoanIndexRoute
  '/admin/Dashboard/Menu': typeof AdminDashboardMenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/Dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/DangKy': typeof DangKyIndexRoute
  '/DangNhap': typeof DangNhapIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/Dashboard/DanhMuc': typeof AdminDashboardDanhMucIndexRoute
  '/admin/Dashboard/LoaiTaiKhoan': typeof AdminDashboardLoaiTaiKhoanIndexRoute
  '/admin/Dashboard/Menu': typeof AdminDashboardMenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/Dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/DangKy/': typeof DangKyIndexRoute
  '/DangNhap/': typeof DangNhapIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/Dashboard/DanhMuc/': typeof AdminDashboardDanhMucIndexRoute
  '/admin/Dashboard/LoaiTaiKhoan/': typeof AdminDashboardLoaiTaiKhoanIndexRoute
  '/admin/Dashboard/Menu/': typeof AdminDashboardMenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/Dashboard'
    | '/DangKy'
    | '/DangNhap'
    | '/admin'
    | '/admin/Dashboard/DanhMuc'
    | '/admin/Dashboard/LoaiTaiKhoan'
    | '/admin/Dashboard/Menu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/Dashboard'
    | '/DangKy'
    | '/DangNhap'
    | '/admin'
    | '/admin/Dashboard/DanhMuc'
    | '/admin/Dashboard/LoaiTaiKhoan'
    | '/admin/Dashboard/Menu'
  id:
    | '__root__'
    | '/'
    | '/admin/Dashboard'
    | '/DangKy/'
    | '/DangNhap/'
    | '/admin/'
    | '/admin/Dashboard/DanhMuc/'
    | '/admin/Dashboard/LoaiTaiKhoan/'
    | '/admin/Dashboard/Menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  DangKyIndexRoute: typeof DangKyIndexRoute
  DangNhapIndexRoute: typeof DangNhapIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DangNhap/': {
      id: '/DangNhap/'
      path: '/DangNhap'
      fullPath: '/DangNhap'
      preLoaderRoute: typeof DangNhapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DangKy/': {
      id: '/DangKy/'
      path: '/DangKy'
      fullPath: '/DangKy'
      preLoaderRoute: typeof DangKyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/Dashboard': {
      id: '/admin/Dashboard'
      path: '/admin/Dashboard'
      fullPath: '/admin/Dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/Dashboard/Menu/': {
      id: '/admin/Dashboard/Menu/'
      path: '/Menu'
      fullPath: '/admin/Dashboard/Menu'
      preLoaderRoute: typeof AdminDashboardMenuIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/LoaiTaiKhoan/': {
      id: '/admin/Dashboard/LoaiTaiKhoan/'
      path: '/LoaiTaiKhoan'
      fullPath: '/admin/Dashboard/LoaiTaiKhoan'
      preLoaderRoute: typeof AdminDashboardLoaiTaiKhoanIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/DanhMuc/': {
      id: '/admin/Dashboard/DanhMuc/'
      path: '/DanhMuc'
      fullPath: '/admin/Dashboard/DanhMuc'
      preLoaderRoute: typeof AdminDashboardDanhMucIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
  }
}

interface AdminDashboardRouteRouteChildren {
  AdminDashboardDanhMucIndexRoute: typeof AdminDashboardDanhMucIndexRoute
  AdminDashboardLoaiTaiKhoanIndexRoute: typeof AdminDashboardLoaiTaiKhoanIndexRoute
  AdminDashboardMenuIndexRoute: typeof AdminDashboardMenuIndexRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardDanhMucIndexRoute: AdminDashboardDanhMucIndexRoute,
  AdminDashboardLoaiTaiKhoanIndexRoute: AdminDashboardLoaiTaiKhoanIndexRoute,
  AdminDashboardMenuIndexRoute: AdminDashboardMenuIndexRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  DangKyIndexRoute: DangKyIndexRoute,
  DangNhapIndexRoute: DangNhapIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
