/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as GioHangIndexRouteImport } from './routes/GioHang/index'
import { Route as DangNhapOTPIndexRouteImport } from './routes/DangNhapOTP/index'
import { Route as DangNhapIndexRouteImport } from './routes/DangNhap/index'
import { Route as DangKyIndexRouteImport } from './routes/DangKy/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CategoryCategoryRouteImport } from './routes/category/$category'
import { Route as AdminDashboardRouteRouteImport } from './routes/admin/Dashboard/route'
import { Route as AdminDashboardProductIndexRouteImport } from './routes/admin/Dashboard/Product/index'
import { Route as AdminDashboardNguoiDungIndexRouteImport } from './routes/admin/Dashboard/NguoiDung/index'
import { Route as AdminDashboardMenuIndexRouteImport } from './routes/admin/Dashboard/Menu/index'
import { Route as AdminDashboardLoaiTaiKhoanIndexRouteImport } from './routes/admin/Dashboard/LoaiTaiKhoan/index'
import { Route as AdminDashboardDonViTinhIndexRouteImport } from './routes/admin/Dashboard/DonViTinh/index'
import { Route as AdminDashboardDanhMucIndexRouteImport } from './routes/admin/Dashboard/DanhMuc/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const GioHangIndexRoute = GioHangIndexRouteImport.update({
  id: '/GioHang/',
  path: '/GioHang/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapOTPIndexRoute = DangNhapOTPIndexRouteImport.update({
  id: '/DangNhapOTP/',
  path: '/DangNhapOTP/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapIndexRoute = DangNhapIndexRouteImport.update({
  id: '/DangNhap/',
  path: '/DangNhap/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyIndexRoute = DangKyIndexRouteImport.update({
  id: '/DangKy/',
  path: '/DangKy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/admin/Dashboard',
  path: '/admin/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardProductIndexRoute =
  AdminDashboardProductIndexRouteImport.update({
    id: '/Product/',
    path: '/Product/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardNguoiDungIndexRoute =
  AdminDashboardNguoiDungIndexRouteImport.update({
    id: '/NguoiDung/',
    path: '/NguoiDung/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardMenuIndexRoute = AdminDashboardMenuIndexRouteImport.update({
  id: '/Menu/',
  path: '/Menu/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardLoaiTaiKhoanIndexRoute =
  AdminDashboardLoaiTaiKhoanIndexRouteImport.update({
    id: '/LoaiTaiKhoan/',
    path: '/LoaiTaiKhoan/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardDonViTinhIndexRoute =
  AdminDashboardDonViTinhIndexRouteImport.update({
    id: '/DonViTinh/',
    path: '/DonViTinh/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardDanhMucIndexRoute =
  AdminDashboardDanhMucIndexRouteImport.update({
    id: '/DanhMuc/',
    path: '/DanhMuc/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/Dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$id': typeof ProductIdRoute
  '/DangKy': typeof DangKyIndexRoute
  '/DangNhap': typeof DangNhapIndexRoute
  '/DangNhapOTP': typeof DangNhapOTPIndexRoute
  '/GioHang': typeof GioHangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/Dashboard/DanhMuc': typeof AdminDashboardDanhMucIndexRoute
  '/admin/Dashboard/DonViTinh': typeof AdminDashboardDonViTinhIndexRoute
  '/admin/Dashboard/LoaiTaiKhoan': typeof AdminDashboardLoaiTaiKhoanIndexRoute
  '/admin/Dashboard/Menu': typeof AdminDashboardMenuIndexRoute
  '/admin/Dashboard/NguoiDung': typeof AdminDashboardNguoiDungIndexRoute
  '/admin/Dashboard/Product': typeof AdminDashboardProductIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/Dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$id': typeof ProductIdRoute
  '/DangKy': typeof DangKyIndexRoute
  '/DangNhap': typeof DangNhapIndexRoute
  '/DangNhapOTP': typeof DangNhapOTPIndexRoute
  '/GioHang': typeof GioHangIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/Dashboard/DanhMuc': typeof AdminDashboardDanhMucIndexRoute
  '/admin/Dashboard/DonViTinh': typeof AdminDashboardDonViTinhIndexRoute
  '/admin/Dashboard/LoaiTaiKhoan': typeof AdminDashboardLoaiTaiKhoanIndexRoute
  '/admin/Dashboard/Menu': typeof AdminDashboardMenuIndexRoute
  '/admin/Dashboard/NguoiDung': typeof AdminDashboardNguoiDungIndexRoute
  '/admin/Dashboard/Product': typeof AdminDashboardProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/Dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$id': typeof ProductIdRoute
  '/DangKy/': typeof DangKyIndexRoute
  '/DangNhap/': typeof DangNhapIndexRoute
  '/DangNhapOTP/': typeof DangNhapOTPIndexRoute
  '/GioHang/': typeof GioHangIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/Dashboard/DanhMuc/': typeof AdminDashboardDanhMucIndexRoute
  '/admin/Dashboard/DonViTinh/': typeof AdminDashboardDonViTinhIndexRoute
  '/admin/Dashboard/LoaiTaiKhoan/': typeof AdminDashboardLoaiTaiKhoanIndexRoute
  '/admin/Dashboard/Menu/': typeof AdminDashboardMenuIndexRoute
  '/admin/Dashboard/NguoiDung/': typeof AdminDashboardNguoiDungIndexRoute
  '/admin/Dashboard/Product/': typeof AdminDashboardProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/Dashboard'
    | '/category/$category'
    | '/product/$id'
    | '/DangKy'
    | '/DangNhap'
    | '/DangNhapOTP'
    | '/GioHang'
    | '/admin'
    | '/admin/Dashboard/DanhMuc'
    | '/admin/Dashboard/DonViTinh'
    | '/admin/Dashboard/LoaiTaiKhoan'
    | '/admin/Dashboard/Menu'
    | '/admin/Dashboard/NguoiDung'
    | '/admin/Dashboard/Product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/Dashboard'
    | '/category/$category'
    | '/product/$id'
    | '/DangKy'
    | '/DangNhap'
    | '/DangNhapOTP'
    | '/GioHang'
    | '/admin'
    | '/admin/Dashboard/DanhMuc'
    | '/admin/Dashboard/DonViTinh'
    | '/admin/Dashboard/LoaiTaiKhoan'
    | '/admin/Dashboard/Menu'
    | '/admin/Dashboard/NguoiDung'
    | '/admin/Dashboard/Product'
  id:
    | '__root__'
    | '/'
    | '/admin/Dashboard'
    | '/category/$category'
    | '/product/$id'
    | '/DangKy/'
    | '/DangNhap/'
    | '/DangNhapOTP/'
    | '/GioHang/'
    | '/admin/'
    | '/admin/Dashboard/DanhMuc/'
    | '/admin/Dashboard/DonViTinh/'
    | '/admin/Dashboard/LoaiTaiKhoan/'
    | '/admin/Dashboard/Menu/'
    | '/admin/Dashboard/NguoiDung/'
    | '/admin/Dashboard/Product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  ProductIdRoute: typeof ProductIdRoute
  DangKyIndexRoute: typeof DangKyIndexRoute
  DangNhapIndexRoute: typeof DangNhapIndexRoute
  DangNhapOTPIndexRoute: typeof DangNhapOTPIndexRoute
  GioHangIndexRoute: typeof GioHangIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/GioHang/': {
      id: '/GioHang/'
      path: '/GioHang'
      fullPath: '/GioHang'
      preLoaderRoute: typeof GioHangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DangNhapOTP/': {
      id: '/DangNhapOTP/'
      path: '/DangNhapOTP'
      fullPath: '/DangNhapOTP'
      preLoaderRoute: typeof DangNhapOTPIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DangNhap/': {
      id: '/DangNhap/'
      path: '/DangNhap'
      fullPath: '/DangNhap'
      preLoaderRoute: typeof DangNhapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DangKy/': {
      id: '/DangKy/'
      path: '/DangKy'
      fullPath: '/DangKy'
      preLoaderRoute: typeof DangKyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/Dashboard': {
      id: '/admin/Dashboard'
      path: '/admin/Dashboard'
      fullPath: '/admin/Dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/Dashboard/Product/': {
      id: '/admin/Dashboard/Product/'
      path: '/Product'
      fullPath: '/admin/Dashboard/Product'
      preLoaderRoute: typeof AdminDashboardProductIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/NguoiDung/': {
      id: '/admin/Dashboard/NguoiDung/'
      path: '/NguoiDung'
      fullPath: '/admin/Dashboard/NguoiDung'
      preLoaderRoute: typeof AdminDashboardNguoiDungIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/Menu/': {
      id: '/admin/Dashboard/Menu/'
      path: '/Menu'
      fullPath: '/admin/Dashboard/Menu'
      preLoaderRoute: typeof AdminDashboardMenuIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/LoaiTaiKhoan/': {
      id: '/admin/Dashboard/LoaiTaiKhoan/'
      path: '/LoaiTaiKhoan'
      fullPath: '/admin/Dashboard/LoaiTaiKhoan'
      preLoaderRoute: typeof AdminDashboardLoaiTaiKhoanIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/DonViTinh/': {
      id: '/admin/Dashboard/DonViTinh/'
      path: '/DonViTinh'
      fullPath: '/admin/Dashboard/DonViTinh'
      preLoaderRoute: typeof AdminDashboardDonViTinhIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/DanhMuc/': {
      id: '/admin/Dashboard/DanhMuc/'
      path: '/DanhMuc'
      fullPath: '/admin/Dashboard/DanhMuc'
      preLoaderRoute: typeof AdminDashboardDanhMucIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
  }
}

interface AdminDashboardRouteRouteChildren {
  AdminDashboardDanhMucIndexRoute: typeof AdminDashboardDanhMucIndexRoute
  AdminDashboardDonViTinhIndexRoute: typeof AdminDashboardDonViTinhIndexRoute
  AdminDashboardLoaiTaiKhoanIndexRoute: typeof AdminDashboardLoaiTaiKhoanIndexRoute
  AdminDashboardMenuIndexRoute: typeof AdminDashboardMenuIndexRoute
  AdminDashboardNguoiDungIndexRoute: typeof AdminDashboardNguoiDungIndexRoute
  AdminDashboardProductIndexRoute: typeof AdminDashboardProductIndexRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardDanhMucIndexRoute: AdminDashboardDanhMucIndexRoute,
  AdminDashboardDonViTinhIndexRoute: AdminDashboardDonViTinhIndexRoute,
  AdminDashboardLoaiTaiKhoanIndexRoute: AdminDashboardLoaiTaiKhoanIndexRoute,
  AdminDashboardMenuIndexRoute: AdminDashboardMenuIndexRoute,
  AdminDashboardNguoiDungIndexRoute: AdminDashboardNguoiDungIndexRoute,
  AdminDashboardProductIndexRoute: AdminDashboardProductIndexRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  CategoryCategoryRoute: CategoryCategoryRoute,
  ProductIdRoute: ProductIdRoute,
  DangKyIndexRoute: DangKyIndexRoute,
  DangNhapIndexRoute: DangNhapIndexRoute,
  DangNhapOTPIndexRoute: DangNhapOTPIndexRoute,
  GioHangIndexRoute: GioHangIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
