/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UuDaiIndexRouteImport } from './routes/UuDai/index'
import { Route as ThongTinIndexRouteImport } from './routes/ThongTin/index'
import { Route as SearchProductIndexRouteImport } from './routes/SearchProduct/index'
import { Route as PhieuMuaHangIndexRouteImport } from './routes/PhieuMuaHang/index'
import { Route as GioHangIndexRouteImport } from './routes/GioHang/index'
import { Route as DonHangIndexRouteImport } from './routes/DonHang/index'
import { Route as DangkyGmailFlowIndexRouteImport } from './routes/DangkyGmailFlow/index'
import { Route as DangNhapOTPIndexRouteImport } from './routes/DangNhapOTP/index'
import { Route as DangNhapIndexRouteImport } from './routes/DangNhap/index'
import { Route as DangKyIndexRouteImport } from './routes/DangKy/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CategoryCategoryRouteImport } from './routes/category/$category'
import { Route as AdminDashboardRouteRouteImport } from './routes/admin/Dashboard/route'
import { Route as AdminDashboardVoucherIndexRouteImport } from './routes/admin/Dashboard/Voucher/index'
import { Route as AdminDashboardProductIndexRouteImport } from './routes/admin/Dashboard/Product/index'
import { Route as AdminDashboardPannerIndexRouteImport } from './routes/admin/Dashboard/Panner/index'
import { Route as AdminDashboardNguoiDungIndexRouteImport } from './routes/admin/Dashboard/NguoiDung/index'
import { Route as AdminDashboardMenuIndexRouteImport } from './routes/admin/Dashboard/Menu/index'
import { Route as AdminDashboardLoaiTaiKhoanIndexRouteImport } from './routes/admin/Dashboard/LoaiTaiKhoan/index'
import { Route as AdminDashboardDonViTinhIndexRouteImport } from './routes/admin/Dashboard/DonViTinh/index'
import { Route as AdminDashboardDonHangIndexRouteImport } from './routes/admin/Dashboard/DonHang/index'
import { Route as AdminDashboardDanhMucIndexRouteImport } from './routes/admin/Dashboard/DanhMuc/index'
import { Route as AdminDashboardBanLamViecIndexRouteImport } from './routes/admin/Dashboard/BanLamViec/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UuDaiIndexRoute = UuDaiIndexRouteImport.update({
  id: '/UuDai/',
  path: '/UuDai/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThongTinIndexRoute = ThongTinIndexRouteImport.update({
  id: '/ThongTin/',
  path: '/ThongTin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchProductIndexRoute = SearchProductIndexRouteImport.update({
  id: '/SearchProduct/',
  path: '/SearchProduct/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhieuMuaHangIndexRoute = PhieuMuaHangIndexRouteImport.update({
  id: '/PhieuMuaHang/',
  path: '/PhieuMuaHang/',
  getParentRoute: () => rootRouteImport,
} as any)
const GioHangIndexRoute = GioHangIndexRouteImport.update({
  id: '/GioHang/',
  path: '/GioHang/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonHangIndexRoute = DonHangIndexRouteImport.update({
  id: '/DonHang/',
  path: '/DonHang/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangkyGmailFlowIndexRoute = DangkyGmailFlowIndexRouteImport.update({
  id: '/DangkyGmailFlow/',
  path: '/DangkyGmailFlow/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapOTPIndexRoute = DangNhapOTPIndexRouteImport.update({
  id: '/DangNhapOTP/',
  path: '/DangNhapOTP/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapIndexRoute = DangNhapIndexRouteImport.update({
  id: '/DangNhap/',
  path: '/DangNhap/',
  getParentRoute: () => rootRouteImport,
} as any)
const DangKyIndexRoute = DangKyIndexRouteImport.update({
  id: '/DangKy/',
  path: '/DangKy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/admin/Dashboard',
  path: '/admin/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardVoucherIndexRoute =
  AdminDashboardVoucherIndexRouteImport.update({
    id: '/Voucher/',
    path: '/Voucher/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardProductIndexRoute =
  AdminDashboardProductIndexRouteImport.update({
    id: '/Product/',
    path: '/Product/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardPannerIndexRoute =
  AdminDashboardPannerIndexRouteImport.update({
    id: '/Panner/',
    path: '/Panner/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardNguoiDungIndexRoute =
  AdminDashboardNguoiDungIndexRouteImport.update({
    id: '/NguoiDung/',
    path: '/NguoiDung/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardMenuIndexRoute = AdminDashboardMenuIndexRouteImport.update({
  id: '/Menu/',
  path: '/Menu/',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardLoaiTaiKhoanIndexRoute =
  AdminDashboardLoaiTaiKhoanIndexRouteImport.update({
    id: '/LoaiTaiKhoan/',
    path: '/LoaiTaiKhoan/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardDonViTinhIndexRoute =
  AdminDashboardDonViTinhIndexRouteImport.update({
    id: '/DonViTinh/',
    path: '/DonViTinh/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardDonHangIndexRoute =
  AdminDashboardDonHangIndexRouteImport.update({
    id: '/DonHang/',
    path: '/DonHang/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardDanhMucIndexRoute =
  AdminDashboardDanhMucIndexRouteImport.update({
    id: '/DanhMuc/',
    path: '/DanhMuc/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)
const AdminDashboardBanLamViecIndexRoute =
  AdminDashboardBanLamViecIndexRouteImport.update({
    id: '/BanLamViec/',
    path: '/BanLamViec/',
    getParentRoute: () => AdminDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/Dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$id': typeof ProductIdRoute
  '/DangKy': typeof DangKyIndexRoute
  '/DangNhap': typeof DangNhapIndexRoute
  '/DangNhapOTP': typeof DangNhapOTPIndexRoute
  '/DangkyGmailFlow': typeof DangkyGmailFlowIndexRoute
  '/DonHang': typeof DonHangIndexRoute
  '/GioHang': typeof GioHangIndexRoute
  '/PhieuMuaHang': typeof PhieuMuaHangIndexRoute
  '/SearchProduct': typeof SearchProductIndexRoute
  '/ThongTin': typeof ThongTinIndexRoute
  '/UuDai': typeof UuDaiIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/Dashboard/BanLamViec': typeof AdminDashboardBanLamViecIndexRoute
  '/admin/Dashboard/DanhMuc': typeof AdminDashboardDanhMucIndexRoute
  '/admin/Dashboard/DonHang': typeof AdminDashboardDonHangIndexRoute
  '/admin/Dashboard/DonViTinh': typeof AdminDashboardDonViTinhIndexRoute
  '/admin/Dashboard/LoaiTaiKhoan': typeof AdminDashboardLoaiTaiKhoanIndexRoute
  '/admin/Dashboard/Menu': typeof AdminDashboardMenuIndexRoute
  '/admin/Dashboard/NguoiDung': typeof AdminDashboardNguoiDungIndexRoute
  '/admin/Dashboard/Panner': typeof AdminDashboardPannerIndexRoute
  '/admin/Dashboard/Product': typeof AdminDashboardProductIndexRoute
  '/admin/Dashboard/Voucher': typeof AdminDashboardVoucherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/Dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$id': typeof ProductIdRoute
  '/DangKy': typeof DangKyIndexRoute
  '/DangNhap': typeof DangNhapIndexRoute
  '/DangNhapOTP': typeof DangNhapOTPIndexRoute
  '/DangkyGmailFlow': typeof DangkyGmailFlowIndexRoute
  '/DonHang': typeof DonHangIndexRoute
  '/GioHang': typeof GioHangIndexRoute
  '/PhieuMuaHang': typeof PhieuMuaHangIndexRoute
  '/SearchProduct': typeof SearchProductIndexRoute
  '/ThongTin': typeof ThongTinIndexRoute
  '/UuDai': typeof UuDaiIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/Dashboard/BanLamViec': typeof AdminDashboardBanLamViecIndexRoute
  '/admin/Dashboard/DanhMuc': typeof AdminDashboardDanhMucIndexRoute
  '/admin/Dashboard/DonHang': typeof AdminDashboardDonHangIndexRoute
  '/admin/Dashboard/DonViTinh': typeof AdminDashboardDonViTinhIndexRoute
  '/admin/Dashboard/LoaiTaiKhoan': typeof AdminDashboardLoaiTaiKhoanIndexRoute
  '/admin/Dashboard/Menu': typeof AdminDashboardMenuIndexRoute
  '/admin/Dashboard/NguoiDung': typeof AdminDashboardNguoiDungIndexRoute
  '/admin/Dashboard/Panner': typeof AdminDashboardPannerIndexRoute
  '/admin/Dashboard/Product': typeof AdminDashboardProductIndexRoute
  '/admin/Dashboard/Voucher': typeof AdminDashboardVoucherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/Dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$id': typeof ProductIdRoute
  '/DangKy/': typeof DangKyIndexRoute
  '/DangNhap/': typeof DangNhapIndexRoute
  '/DangNhapOTP/': typeof DangNhapOTPIndexRoute
  '/DangkyGmailFlow/': typeof DangkyGmailFlowIndexRoute
  '/DonHang/': typeof DonHangIndexRoute
  '/GioHang/': typeof GioHangIndexRoute
  '/PhieuMuaHang/': typeof PhieuMuaHangIndexRoute
  '/SearchProduct/': typeof SearchProductIndexRoute
  '/ThongTin/': typeof ThongTinIndexRoute
  '/UuDai/': typeof UuDaiIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/Dashboard/BanLamViec/': typeof AdminDashboardBanLamViecIndexRoute
  '/admin/Dashboard/DanhMuc/': typeof AdminDashboardDanhMucIndexRoute
  '/admin/Dashboard/DonHang/': typeof AdminDashboardDonHangIndexRoute
  '/admin/Dashboard/DonViTinh/': typeof AdminDashboardDonViTinhIndexRoute
  '/admin/Dashboard/LoaiTaiKhoan/': typeof AdminDashboardLoaiTaiKhoanIndexRoute
  '/admin/Dashboard/Menu/': typeof AdminDashboardMenuIndexRoute
  '/admin/Dashboard/NguoiDung/': typeof AdminDashboardNguoiDungIndexRoute
  '/admin/Dashboard/Panner/': typeof AdminDashboardPannerIndexRoute
  '/admin/Dashboard/Product/': typeof AdminDashboardProductIndexRoute
  '/admin/Dashboard/Voucher/': typeof AdminDashboardVoucherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/Dashboard'
    | '/category/$category'
    | '/product/$id'
    | '/DangKy'
    | '/DangNhap'
    | '/DangNhapOTP'
    | '/DangkyGmailFlow'
    | '/DonHang'
    | '/GioHang'
    | '/PhieuMuaHang'
    | '/SearchProduct'
    | '/ThongTin'
    | '/UuDai'
    | '/admin'
    | '/admin/Dashboard/BanLamViec'
    | '/admin/Dashboard/DanhMuc'
    | '/admin/Dashboard/DonHang'
    | '/admin/Dashboard/DonViTinh'
    | '/admin/Dashboard/LoaiTaiKhoan'
    | '/admin/Dashboard/Menu'
    | '/admin/Dashboard/NguoiDung'
    | '/admin/Dashboard/Panner'
    | '/admin/Dashboard/Product'
    | '/admin/Dashboard/Voucher'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/Dashboard'
    | '/category/$category'
    | '/product/$id'
    | '/DangKy'
    | '/DangNhap'
    | '/DangNhapOTP'
    | '/DangkyGmailFlow'
    | '/DonHang'
    | '/GioHang'
    | '/PhieuMuaHang'
    | '/SearchProduct'
    | '/ThongTin'
    | '/UuDai'
    | '/admin'
    | '/admin/Dashboard/BanLamViec'
    | '/admin/Dashboard/DanhMuc'
    | '/admin/Dashboard/DonHang'
    | '/admin/Dashboard/DonViTinh'
    | '/admin/Dashboard/LoaiTaiKhoan'
    | '/admin/Dashboard/Menu'
    | '/admin/Dashboard/NguoiDung'
    | '/admin/Dashboard/Panner'
    | '/admin/Dashboard/Product'
    | '/admin/Dashboard/Voucher'
  id:
    | '__root__'
    | '/'
    | '/admin/Dashboard'
    | '/category/$category'
    | '/product/$id'
    | '/DangKy/'
    | '/DangNhap/'
    | '/DangNhapOTP/'
    | '/DangkyGmailFlow/'
    | '/DonHang/'
    | '/GioHang/'
    | '/PhieuMuaHang/'
    | '/SearchProduct/'
    | '/ThongTin/'
    | '/UuDai/'
    | '/admin/'
    | '/admin/Dashboard/BanLamViec/'
    | '/admin/Dashboard/DanhMuc/'
    | '/admin/Dashboard/DonHang/'
    | '/admin/Dashboard/DonViTinh/'
    | '/admin/Dashboard/LoaiTaiKhoan/'
    | '/admin/Dashboard/Menu/'
    | '/admin/Dashboard/NguoiDung/'
    | '/admin/Dashboard/Panner/'
    | '/admin/Dashboard/Product/'
    | '/admin/Dashboard/Voucher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  ProductIdRoute: typeof ProductIdRoute
  DangKyIndexRoute: typeof DangKyIndexRoute
  DangNhapIndexRoute: typeof DangNhapIndexRoute
  DangNhapOTPIndexRoute: typeof DangNhapOTPIndexRoute
  DangkyGmailFlowIndexRoute: typeof DangkyGmailFlowIndexRoute
  DonHangIndexRoute: typeof DonHangIndexRoute
  GioHangIndexRoute: typeof GioHangIndexRoute
  PhieuMuaHangIndexRoute: typeof PhieuMuaHangIndexRoute
  SearchProductIndexRoute: typeof SearchProductIndexRoute
  ThongTinIndexRoute: typeof ThongTinIndexRoute
  UuDaiIndexRoute: typeof UuDaiIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UuDai/': {
      id: '/UuDai/'
      path: '/UuDai'
      fullPath: '/UuDai'
      preLoaderRoute: typeof UuDaiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ThongTin/': {
      id: '/ThongTin/'
      path: '/ThongTin'
      fullPath: '/ThongTin'
      preLoaderRoute: typeof ThongTinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/SearchProduct/': {
      id: '/SearchProduct/'
      path: '/SearchProduct'
      fullPath: '/SearchProduct'
      preLoaderRoute: typeof SearchProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PhieuMuaHang/': {
      id: '/PhieuMuaHang/'
      path: '/PhieuMuaHang'
      fullPath: '/PhieuMuaHang'
      preLoaderRoute: typeof PhieuMuaHangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/GioHang/': {
      id: '/GioHang/'
      path: '/GioHang'
      fullPath: '/GioHang'
      preLoaderRoute: typeof GioHangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DonHang/': {
      id: '/DonHang/'
      path: '/DonHang'
      fullPath: '/DonHang'
      preLoaderRoute: typeof DonHangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DangkyGmailFlow/': {
      id: '/DangkyGmailFlow/'
      path: '/DangkyGmailFlow'
      fullPath: '/DangkyGmailFlow'
      preLoaderRoute: typeof DangkyGmailFlowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DangNhapOTP/': {
      id: '/DangNhapOTP/'
      path: '/DangNhapOTP'
      fullPath: '/DangNhapOTP'
      preLoaderRoute: typeof DangNhapOTPIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DangNhap/': {
      id: '/DangNhap/'
      path: '/DangNhap'
      fullPath: '/DangNhap'
      preLoaderRoute: typeof DangNhapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/DangKy/': {
      id: '/DangKy/'
      path: '/DangKy'
      fullPath: '/DangKy'
      preLoaderRoute: typeof DangKyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/Dashboard': {
      id: '/admin/Dashboard'
      path: '/admin/Dashboard'
      fullPath: '/admin/Dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/Dashboard/Voucher/': {
      id: '/admin/Dashboard/Voucher/'
      path: '/Voucher'
      fullPath: '/admin/Dashboard/Voucher'
      preLoaderRoute: typeof AdminDashboardVoucherIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/Product/': {
      id: '/admin/Dashboard/Product/'
      path: '/Product'
      fullPath: '/admin/Dashboard/Product'
      preLoaderRoute: typeof AdminDashboardProductIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/Panner/': {
      id: '/admin/Dashboard/Panner/'
      path: '/Panner'
      fullPath: '/admin/Dashboard/Panner'
      preLoaderRoute: typeof AdminDashboardPannerIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/NguoiDung/': {
      id: '/admin/Dashboard/NguoiDung/'
      path: '/NguoiDung'
      fullPath: '/admin/Dashboard/NguoiDung'
      preLoaderRoute: typeof AdminDashboardNguoiDungIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/Menu/': {
      id: '/admin/Dashboard/Menu/'
      path: '/Menu'
      fullPath: '/admin/Dashboard/Menu'
      preLoaderRoute: typeof AdminDashboardMenuIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/LoaiTaiKhoan/': {
      id: '/admin/Dashboard/LoaiTaiKhoan/'
      path: '/LoaiTaiKhoan'
      fullPath: '/admin/Dashboard/LoaiTaiKhoan'
      preLoaderRoute: typeof AdminDashboardLoaiTaiKhoanIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/DonViTinh/': {
      id: '/admin/Dashboard/DonViTinh/'
      path: '/DonViTinh'
      fullPath: '/admin/Dashboard/DonViTinh'
      preLoaderRoute: typeof AdminDashboardDonViTinhIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/DonHang/': {
      id: '/admin/Dashboard/DonHang/'
      path: '/DonHang'
      fullPath: '/admin/Dashboard/DonHang'
      preLoaderRoute: typeof AdminDashboardDonHangIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/DanhMuc/': {
      id: '/admin/Dashboard/DanhMuc/'
      path: '/DanhMuc'
      fullPath: '/admin/Dashboard/DanhMuc'
      preLoaderRoute: typeof AdminDashboardDanhMucIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/Dashboard/BanLamViec/': {
      id: '/admin/Dashboard/BanLamViec/'
      path: '/BanLamViec'
      fullPath: '/admin/Dashboard/BanLamViec'
      preLoaderRoute: typeof AdminDashboardBanLamViecIndexRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
  }
}

interface AdminDashboardRouteRouteChildren {
  AdminDashboardBanLamViecIndexRoute: typeof AdminDashboardBanLamViecIndexRoute
  AdminDashboardDanhMucIndexRoute: typeof AdminDashboardDanhMucIndexRoute
  AdminDashboardDonHangIndexRoute: typeof AdminDashboardDonHangIndexRoute
  AdminDashboardDonViTinhIndexRoute: typeof AdminDashboardDonViTinhIndexRoute
  AdminDashboardLoaiTaiKhoanIndexRoute: typeof AdminDashboardLoaiTaiKhoanIndexRoute
  AdminDashboardMenuIndexRoute: typeof AdminDashboardMenuIndexRoute
  AdminDashboardNguoiDungIndexRoute: typeof AdminDashboardNguoiDungIndexRoute
  AdminDashboardPannerIndexRoute: typeof AdminDashboardPannerIndexRoute
  AdminDashboardProductIndexRoute: typeof AdminDashboardProductIndexRoute
  AdminDashboardVoucherIndexRoute: typeof AdminDashboardVoucherIndexRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardBanLamViecIndexRoute: AdminDashboardBanLamViecIndexRoute,
  AdminDashboardDanhMucIndexRoute: AdminDashboardDanhMucIndexRoute,
  AdminDashboardDonHangIndexRoute: AdminDashboardDonHangIndexRoute,
  AdminDashboardDonViTinhIndexRoute: AdminDashboardDonViTinhIndexRoute,
  AdminDashboardLoaiTaiKhoanIndexRoute: AdminDashboardLoaiTaiKhoanIndexRoute,
  AdminDashboardMenuIndexRoute: AdminDashboardMenuIndexRoute,
  AdminDashboardNguoiDungIndexRoute: AdminDashboardNguoiDungIndexRoute,
  AdminDashboardPannerIndexRoute: AdminDashboardPannerIndexRoute,
  AdminDashboardProductIndexRoute: AdminDashboardProductIndexRoute,
  AdminDashboardVoucherIndexRoute: AdminDashboardVoucherIndexRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  CategoryCategoryRoute: CategoryCategoryRoute,
  ProductIdRoute: ProductIdRoute,
  DangKyIndexRoute: DangKyIndexRoute,
  DangNhapIndexRoute: DangNhapIndexRoute,
  DangNhapOTPIndexRoute: DangNhapOTPIndexRoute,
  DangkyGmailFlowIndexRoute: DangkyGmailFlowIndexRoute,
  DonHangIndexRoute: DonHangIndexRoute,
  GioHangIndexRoute: GioHangIndexRoute,
  PhieuMuaHangIndexRoute: PhieuMuaHangIndexRoute,
  SearchProductIndexRoute: SearchProductIndexRoute,
  ThongTinIndexRoute: ThongTinIndexRoute,
  UuDaiIndexRoute: UuDaiIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
